version: '3.7'

services:

    web:
	image: nginx:latest
	ports:
	- "8080:80"
	volumes:
	- ./src:/usr/share/nginx/html
links:
- php

    mariadb:
        image: mariadb:10.6.8
        volumes:
            - vol-mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "myuser"
            MYSQL_PASSWORD: "mypass"
            MYSQL_DATABASE: "mydb"
